package com.wtf.app.model.enums;

public enum TaskType {

    WHATSAPP_FETCH_CONTACTS(SocialType.WHATSAPP, FlowType.FETCH_ALL_CONTACTS_AND_GROUPS),
    WHATSAPP_JOIN_NEW_GROUPS(SocialType.WHATSAPP,FlowType.FETCH_ALL_CONTACTS_AND_GROUPS),
    WHATSAPP_BROADCAST_AD_TO_GROUPS(SocialType.WHATSAPP,FlowType.BROADCAST_SELF_SKILLSET_AD_TO_GROUPS),
    WHATSAPP_SYNC_SENT_FOR_THE_DAY(SocialType.WHATSAPP,FlowType.FETCH_ALL_CONTACTS_AND_GROUPS),
    WHATSAPP_BROADCAST_AD_TO_CONSULTANTS(SocialType.WHATSAPP,FlowType.BROADCAST_AD_TO_CONSULTANTS),
    WHATSAPP_BROADCAST_AD_TO_UNKNOWN_USA_PERSONS(SocialType.WHATSAPP,FlowType.BROADCAST_AD_TO_CONSULTANTS),


    FACEBOOK_FETCH_CONTACTS(SocialType.FACEBOOK,FlowType.FETCH_ALL_CONTACTS_AND_GROUPS),
    FACEBOOK_JOIN_NEW_GROUPS(SocialType.FACEBOOK,FlowType.FETCH_ALL_CONTACTS_AND_GROUPS),
    FACEBOOK_BROADCAST_AD(SocialType.FACEBOOK,FlowType.BROADCAST_SELF_SKILLSET_AD_TO_GROUPS),
    FACEBOOK_BROADCAST_SENSITIVE_AD(SocialType.FACEBOOK,FlowType.BROADCAST_SELF_SKILLSET_AD_TO_SENSITIVE_FB_GROUPS_ANNONYM),


    TELEGRAM_FETCH_CONTACTS(SocialType.TELEGRAM,FlowType.FETCH_ALL_CONTACTS_AND_GROUPS),
    TELEGRAM_JOIN_NEW_GROUPS(SocialType.TELEGRAM,FlowType.FETCH_ALL_CONTACTS_AND_GROUPS),
    TELEGRAM_BROADCAST_AD(SocialType.TELEGRAM,FlowType.BROADCAST_SELF_SKILLSET_AD_TO_GROUPS),
    TELEGRAM_SYNC_SENT_FOR_THE_DAY(SocialType.TELEGRAM,FlowType.FETCH_ALL_CONTACTS_AND_GROUPS),
    PARALLEL_TASKS(SocialType.DEFAULT,FlowType.DEFAULT),
    DEFAULT(SocialType.DEFAULT,FlowType.DEFAULT);



    private final SocialType socialType;
    private final FlowType flowType;

    TaskType(SocialType socialType, FlowType flowType) {
        this.flowType = flowType;
        this.socialType = socialType;
    }

    public SocialType getSocialType() {
        return socialType;
    }

    public FlowType getFlowType() {
        return flowType;
    }
}
