package com.wtf.app.app.enums;

public enum EnumActivityToPerform {
	ARCHIVE_SUPPORT_GROUP, JOIN_NEW_ELIGIBLE_GROUPS, EXTRACT_CONTACTS_FROM_SUPPORT_GROUPS, BROADCAST_ON_EACH_GROUP, BROADCAST_ON_EACH_US_INDIVIDUAL_CONSULTANT, DEFAULT
}
